=== fcdl94/VehicleTracking/xsd/vehicleTracking.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.vechicleTrackingSystem.org/model" xmlns:s="http://www.vechicleTrackingSystem.org/model" elementFormDefault="qualified">

<!-- merge of path and graph definition for the response -->
<!-- We chose to have a response with embedded both the path and the relative information of the graph (partial) -->
	<element name="pathFull" >
		<complexType>
			<sequence>
				<element ref="s:graph"/>
				<element ref="s:path" />
			</sequence>
		</complexType>
		<keyref name="pathRefKey" refer="s:nodeKey">
			<selector xpath="pathResponse/path" />
			<field xpath="node" />
		</keyref>
	</element> 

<!-- Graph definition -->
<!-- Basic type of the graph is node which can be extended in parking area and route.
		Each type of extension have its own constraint that can be defined independently 
		The nodes are bound with connection which represent the edge of the graph.
		Each arc (connection) is oriented so I assumed each connection is unidirectional (to represent one-way route)
-->
	<element name="graph" type="s:graphType" >
		<key name="nodeKey">
			<selector xpath="graph/node" />
			<field xpath="@ID" />
		</key>
		<keyref name="connectionNode1" refer="s:nodeKey">
			<selector xpath="graph/connection" />
			<field xpath="node1" />
		</keyref>
		<keyref name="connectionNode2" refer="s:nodeKey">
			<selector xpath="graph/connection" />
			<field xpath="node2" />
		</keyref>
	</element>
	
	
	<complexType name="graphType" >
		<sequence>
			<element name="node" type="s:nodeType" maxOccurs="unbounded"/>
			<element name="connection" type="s:connectionType" maxOccurs="unbounded" />
		</sequence>
	</complexType>	
	
	<complexType name="nodeType">
		<sequence>
			<element name="name" type="string" />
			<element name="vehicleNumber" type="integer" />
		</sequence>
		<attribute name="ID" type="string" />
	</complexType>
	
	<complexType name="roadType">
	<!-- End Point represent the fact that a route can be an entry/exit point of the restricted area
			the max vehicle constraint limits the number of car in that route-->
		<complexContent>
			<extension base="s:nodeType">
				<sequence>
					<element name="endpoint" type="boolean" minOccurs="0" />
					<element name="maxVehicle" type="positiveInteger" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
   
	<complexType name="parkingAreaType">
	<!-- The max vehicle constraint represent the number of parking spot -->
		<complexContent>
			<extension base="s:nodeType">
				<sequence>
					<element name="maxVehicle" type="positiveInteger" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	
	<complexType name="connectionType" >
	 	<sequence>
	   		<element name="from" type="string" />
	   		<element name="to" type="string" />
	   	</sequence>
	</complexType>

<!-- vehicle definition -->
	<!-- each vehicle has 
		position (a string referencing the position in graph) 
		state indicating if the vehicle is parked or in transit
		the path that is it following
		entry time is the time while the vehicle entered the system
		last update is the time in which the last position is received (at starting point this field is equal to entry time)
		The plate number is not the ID because in the specification is request the assignment of an ID by the service 
			also I kept a general string as a type for plate due to the different representations of plate code in each country -->
	<element name="vehicle" type="s:vehicleType" />
	<complexType name="vehicleType" >
		<sequence>
			<element name="currentPosition" type="string" />
			<element name="state" type="s:state" />
			<element ref="s:path" />
			<element name="entry_time" type="dateTime" />
			<element name="last_update" type="dateTime" />
			<element name="plateNumber" type="string" />
		</sequence>
		<attribute name="ID" type="string" />
	</complexType>
	
	<complexType name="car">
		<complexContent>
			<extension base="s:vehicleType">
				<sequence>
					<!-- something in the future -->
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<simpleType name="state" >
		<restriction base="string">
			<enumeration value="transit" />
			<enumeration value="parked" />
		</restriction>
	</simpleType>
	
	
<!-- PATH DEFINITION -->
	<element name="path" type="s:pathType" />
	
	<complexType name="pathType">
		<sequence>
			<element name="node" type="s:nodeInPath" minOccurs="2" maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="nodeInPath">
		<simpleContent>
			<extension base="string">
				<attribute name="sequenceNum" type="positiveInteger" />
			</extension>
		</simpleContent>
	</complexType>

</schema>

=== fcdl94/VehicleTracking/xsd/model.xml
<?xml version="1.0" encoding="utf-8"?>

<graph 
	xmlns="http://www.vechicleTrackingSystem.org/model" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.vechicleTrackingSystem.org/model vehicleTracking.xsd">
  
  <node ID="road1" xsi:type="roadType">
    <name>street A</name>
    <vehicleNumber>0</vehicleNumber>
    <endpoint > true </endpoint>
    <maxVehicle> 10 </maxVehicle>
  </node>
  
   <node ID="road2" xsi:type="roadType">
    <name>street B</name>
    <vehicleNumber>0</vehicleNumber>
    <maxVehicle> 10 </maxVehicle>
  </node>
  
  <node ID="road3" xsi:type="roadType">
    <name>street C</name>
    <vehicleNumber>0</vehicleNumber>
    <maxVehicle> 10 </maxVehicle>
  </node>
  
  <node ID="road4" xsi:type="roadType">
    <name>street D</name>
    <vehicleNumber>0</vehicleNumber>
    <endpoint >true </endpoint>
    <maxVehicle> 10 </maxVehicle>
  </node>
  
  <node ID="road2" xsi:type="roadType">
    <name>street B</name>
    <vehicleNumber>0</vehicleNumber>
    <maxVehicle> 10 </maxVehicle>
  </node>
  
  <node ID="area1" xsi:type="parkingAreaType">
    <name>Area 1</name>
    <vehicleNumber>0</vehicleNumber>
    <maxVehicle> 10 </maxVehicle>
  </node>
  
  <node ID="area2" xsi:type="parkingAreaType">
    <name>Area B</name>
    <vehicleNumber>0</vehicleNumber>
    <maxVehicle> 10 </maxVehicle>
  </node>
  
  <connection>
    <from>road1</from>
    <to>road2</to>
  </connection>

  <connection>
    <from>road2</from>
    <to>road1</to>
  </connection>

  <connection>
    <from>road1</from>
    <to>road3</to>
  </connection>

  <connection>
    <from>road3</from>
    <to>road4</to>
  </connection>

  <connection>
    <from>road4</from>
    <to>road2</to>
  </connection>
  
  <connection>
    <from>area1</from>
    <to>road1</to>
  </connection>
  
  <connection>
    <from>road1</from>
    <to>area1</to>
  </connection>

  <connection>
    <from>road3</from>
    <to>area1</to>
  </connection>

  <connection>
    <from>area1</from>
    <to>road4</to>
  </connection>

  <connection>
    <from>road4</from>
    <to>area2</to>
  </connection>

  <connection>
    <from>area2</from>
    <to>road2</to>
  </connection>


</graph>
